services:
  discord-widget:
    build: .
    container_name: discord-widget-updater
    restart: unless-stopped
    ports:
      - "3456:3456"
    environment:
      - APP_ID=${APP_ID}
      - USER_ID=${USER_ID}
      - BOT_TOKEN=${BOT_TOKEN}
